// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9pUEbAJhYqtPyAVUQZDVXI7YOtu99iI',
    appId: '1:171680808501:web:f435886a0964ab6e0d7b7c',
    messagingSenderId: '171680808501',
    projectId: 'dolabim-da043',
    authDomain: 'dolabim-da043.firebaseapp.com',
    storageBucket: 'dolabim-da043.firebasestorage.app',
    measurementId: 'G-3E59VPGLEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAALC-5OB0Q_bMH9RKQq8eSn9nzdYtM68Q',
    appId: '1:171680808501:android:261f411c24c3b23a0d7b7c',
    messagingSenderId: '171680808501',
    projectId: 'dolabim-da043',
    storageBucket: 'dolabim-da043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjLKuQ4TFek0lDTSmaFcM4deN4sFkNjo',
    appId: '1:171680808501:ios:0c8001462c676e7e0d7b7c',
    messagingSenderId: '171680808501',
    projectId: 'dolabim-da043',
    storageBucket: 'dolabim-da043.firebasestorage.app',
    iosBundleId: 'com.example.dolabim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjLKuQ4TFek0lDTSmaFcM4deN4sFkNjo',
    appId: '1:171680808501:ios:0c8001462c676e7e0d7b7c',
    messagingSenderId: '171680808501',
    projectId: 'dolabim-da043',
    storageBucket: 'dolabim-da043.firebasestorage.app',
    iosBundleId: 'com.example.dolabim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9pUEbAJhYqtPyAVUQZDVXI7YOtu99iI',
    appId: '1:171680808501:web:efbc5d0908faa7950d7b7c',
    messagingSenderId: '171680808501',
    projectId: 'dolabim-da043',
    authDomain: 'dolabim-da043.firebaseapp.com',
    storageBucket: 'dolabim-da043.firebasestorage.app',
    measurementId: 'G-1VTHLMF0DM',
  );
}
